spring:
  application:
    name: care-tip-service
  profiles:
    active: k8
  jackson:
    default-property-inclusion: non_empty

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never